BEGIN;

ALTER TABLE sales_orders
  ADD COLUMN IF NOT EXISTS pb1_amount NUMERIC(14,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS service_charge_amount NUMERIC(14,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ppn_amount NUMERIC(14,2) NOT NULL DEFAULT 0;

COMMIT;
